### PR TITLE
Using one ntfs_system_decompression_ctx for all reads of file

### PR DESCRIPTION
**Pull request by MikalaiR**

### CODE REVIEW

**Comment by ebiggers** [comment]
The reason I hadn't done this yet is that I don't think this is guaranteed to work.  The system decompression context holds a reference to the open compressed data attribute, which holds a reference to the open inode.  However, NTFS-3G does not guarantee that the inode remains open between successive reads.

**Comment by MikalaiR** [comment]
> The system decompression context holds a reference to the open compressed data 
> 
> attribute

Fixed.

**Comment by ebiggers** [comment]
Interesting changes.  They will need some cleanup before they can be merged, though.
- One feature per pull request, please.  Using one decompression context per open should be one pull request; addition of write support should be another.
- Please revert unrelated, nonfunctional changes such as formatting changes, replacing `if` statements with `switch` statements, etc.  If you really want to make such changes they should be done as a separate "cleanup" pull request.
- Please indent all new code consistently with the existing code.
- Please squash the commits on each branch into one and include a proper commit message that describes the problem being solved and how you solved it.

Thanks!

**Comment by MikalaiR** [comment]
Done.

**Comment by ebiggers** [comment]
Hi Mikalai,

I finally had time to properly clean up, fix, and test this.  The overall solution (relying on the inode being passed into `->read()`) does indeed work, though it exposed a bug in `lowntfs-3g` for which I proposed an NTFS-3G patch.

I committed my reworked version of the change as cd6017fbab1fc5d5b327bf1e0dd64a2187dc70e1.

Thanks!

**Pull request closed without merging**
